requirements.txt

目前 revChatGPT 0.0.47 版本已经移除了 `AsyncChatbot, generate_uuid` 两个API
只剩下了 `Chatbot`
https://github.com/acheong08/ChatGPT/blob/97b324c09133d6175a9538496e9302e397bbc547/src/revChatGPT/ChatGPT.py#L24
执行
https://github.com/lss233/chatgpt-mirai-qq-bot/blob/2fbafaacab44f492717f6b3b7137a1d1bf44dc11/chatbot.py#L1
```
from revChatGPT.revChatGPT import AsyncChatbot, generate_uuid
```
会 raise `revChatGPT.revChatGPT`  module not found 
我看了下 `ChatGPT` 内部没有很大变化，不过在迁移代码之前，建议先固定pip install 的 revChatGPT 版本
------
哦对了，非常感谢你们非常有帮助的代码！！🥳🥳🥳🥳🥳

Update revChatGPT version

---

requirements.txt

revChatGPT１.０之后的新版本删除了tls_clinet等依赖，导致报错no module named tls_client。因此需要将其去掉的依赖加到requirement.txt中。
经测试，按当前requirement.txt会安装revChatGPT最新1.1.0版本，可以正常运行。

add missed requirements

---

assets/texttoimg/css/default.css
utils/text_to_img.py

1、将文件编码改为UTF-8，以修复UnicodeEncodeError
例子：
用户：`将“忧郁的乌龟”分别翻译为繁体中文、日文、韩文、英文`
机器人理想状态：
```
繁体中文：憂鬱的烏龜
日文：憂鬱なカメ
韓文：우울한 거북이
英文：Melancholy Turtle
```
实际报错：`UnicodeEncodeError: 'gbk' codec can't encode character '\uc6b0' in position 5067:`
然后回退到备用模式
2、wkhtmltoimage似乎对overflow-x属性兼容不好，在Windows上会使得图片过长，且中文越多图片越长
https://github.com/lss233/chatgpt-mirai-qq-bot/issues/286

1、修复编码错误；2、修复图片过长

---

README.md
assets/texttoimg/css/default.css
assets/texttoimg/template.html
utils/text_to_img.py

1、通过定义REM的字体大小来调节全部文本大小，将CSS中font-size全部改为rem定义
2、在template.html中新增一个font-face来接受自定义字体，当字体不存在时仍能使用系统字体
3、更改了readme中关于图片模式的描述（包括新支持的文字大小和字体，以及原来的代码图片宽度是会影响HTML图片渲染模式的图片大小的，并非备用模式）

使HTML图片渲染模式下可调节文字大小和字体

---

adapter/ms/bing.py
requirements.txt

Bing 宣布 Bing Chat 单个会话里的连续提问次数提升至 15 条，每个账户每天最多可以提问 150 条
上游依赖EdgeGPT修复了一个导致`KeyError: 'messages'`的错误

1、Bing会话限制已提升至15条 2、更新上游修复Bing无限结束会话

---

README.md
adapter/botservice.py
adapter/chatgpt/web.py
adapter/google/bard.py
adapter/ms/bing.py
adapter/openai/api.py
adapter/quora/poe.py
config.py
conversation.py
manager/bot.py
requirements.txt

Feat support poe

---

utils/text_to_speech.py
utils/vits_tts.py

你好！我在代码中修复了以下问题：
1、`output_file.name`获取到的是文件的完整名称，直接加".silk"导致后缀重复
2、由于映射表更新，在此修复了获取vits角色id失败的问题

fix:修复映射表校验、后缀重复

---

assets/texttoimg/css/default.css

修复图片模式下文字超出设定宽度

---

config.py
drawing/sdwebui.py

某些情况下stable diffusion api需要设置账号密码，以增强使用期间的安全性。
使用方法：
如果自己的sd api设置了账号密码，就在config文件的[sdwebui]标签下添加（注意账号和密码中间的冒号是英文的冒号）：
Authorization = 账号:密码

针对stable diffusion api有账号密码的情况做出相应完善

---

bot.py
config.py
platforms/wecom_bot.py
requirements.txt

增加企业微信支持，使用 [wechatpy](https://github.com/wechatpy/wechatpy) 实现
```
[wecom]
host = "0.0.0.0"
port = 5001
debug = false
corp_id = "ww***"
agent_id = 1000001
secret = "abc***"
token = "abc***"
encoding_aes_key = "abc***"
```
由于企业微信限制，目前仅能实现在同企业单聊 App 使用
可以将企业微信添加至微信手机版来实现直接在微信中调用
**如果需要发送语音，请将系统 ffmpeg 升级至 5.x 或更新**

feat: support wecom

---

Dockerfile-cn
manager/bot.py

- Fix #722 
- 增加`Dockerfile-cn`，方便国内用户打包docker镜像，apt源为阿里源，pip源为清华源

Fix slack-claude 在ping命令中不显示

---

bot.py
config.py
framework/platforms/http_service.py
framework/platforms/http_service_legacy.py
framework/platforms/onebot_bot.py
framework/platforms/wecom_bot.py
framework/tts/tts.py

This refactor is a part of #755 .
进行了以下修改：
* 将 OneBot、Wecom 和 HTTP API 的 Quart 实例合并为一个
* 设计了新的 HTTP API，旧的 HTTP API 将会在不久后移除
| 请求方法 | URL |
| ------ | --- |
| POST   | /v1/conversation |
| 字段        | 类型     | 必填  | 描述                                                                    |
| ------------ | ------- | -------- | --------------------------------------------------------------------- |
| session_id   | string  | Yes      | 会话 ID。                     |
| user_id      | string  | Yes      | 用户 ID。          |
| group_id     | string  | No       | 群组 ID（如果适用）。 |
| nickname     | string  | No       | 用户昵称。                  |
| messages     | Message[]   | Yes      | 表示用户输入的消息对象数组。             |
| 字段  | 类型   | 必填 | 描述                                |
| ------ | ------ | -------- | …

refactor: HTTP API 重构

---

drawing/sdwebui.py

修复图生图init_images字段为空的bug
- 需要调用get_bytes方法，才能获取到base64字段内容
过滤图生图提示词中的额外字符
- 消息链显示字符串中有“[图片]”字样，需要过滤
Fixes #839

修复图生图init_images字段为空的bug, 过滤图生图提示词中的额外字符

---

adapter/chatgpt/api.py
config.py

Add new models released by OpenAI today:
- "gpt-3.5-turbo-0613" 
- "gpt-3.5-turbo-16k"
- "gpt-3.5-turbo-16k-0613"
- "gpt-4-0613"
- "gpt-4-32k-0613"

Add support for new GPT 3.5 and 4 models released by OpenAI today [6/13]

---

adapter/google/bard.py

Bard 返回数据的组织方式发生了变化，脚本在读取数据时出现问题。原先代码 `result = data[0][0]` 会引发 `TypeError` 错误。分析返回数据，将代码修改为 `result = data[4][0][1][0]`可以解决问题。
修改后机器人能够正常运行。
数据一：
```python
[None, ['c_2a0329c4aaaaaaaa', 'r_2a0329c4aaaaaaaa'],
[
['Hi', 1],
['Why do I say hi?', 4],
['What is hello or hi?', 4]
], None, [
['rc_2a0329c4aaaaaaaa', ['Hi there! How can I help you today?'],
[], None, None, None, True, None, None, 'en', None, None, [None, None, None, None, None, [
[]
]], None, False
]
], None, None, None, 'US'
]
```
```python
result = 'Hi there! How can I help you today?'
```
数据二：
```python
[None, ['c_e429c5f9aaaaaaaa', 'r_e429c5f9aaaaaaaa'],
[
['How do you read Japanese date format?', 4],
['How do Japanese calculate years?', 4]
], None, [
['rc_f6037659aaaaaaaa', ["Alright, I'm all ears. What would you like to ask …
```

fix: 更新 Bard 脚本以正确获取数据

---

adapter/ms/bing.py
conversation.py
requirements.txt

Reverts lss233/chatgpt-mirai-qq-bot#1041

Revert "更新edgeGPT"

---

Dockerfile
requirements.txt

fix: old poe-api cause AttributeError #1081

---

Dockerfile

fix: remove binutils will also remove gcc

---

manager/ratelimit.py

前段时间给用户使用的过程中发现一个问题（我设置所有用户的额度为20条/小时），如果某用户第一天晚上八点时对话了18条，且九点后一直到次日八点这个用户没有继续进行对话，那么第二天八点时，该用户将继承这个18/20的使用额度，导致该用户在今天八点时只能对话2条。因此对于`chatgpt-mirai-qq-bot/manager/ratelimit.py`函数进行修改：
- 在rate_usage.json数据库中，记录`day`的属性。初始化时，`usage = {'type': _type, 'id': _id, 'count': 0, 'time': current_time, 'day': current_day}`
- 在`get_usage`函数中，添加了根据天数`day`删除过期的记录的判断方案。

完善了删除过期额度的方案，避免第二天继承上一天没使用完的额度

---

utils/text_to_img.py

In accordance with [Pillow#7080](https://github.com/python-pillow/Pillow/pull/7080).
- Resolve #1175
- Resolve #1088

Replace deprecated FreeTypeFont.getsize()

---

README.md

添加 SUCCESS 和 FAILED 的情况
{"result": "SUCCESS", "message": [], "voice": [], "image": []}
{"result": "FAILED", "message": ["\u6ca1\u6709\u66f4\u591a\u4e86\uff01"], "voice": [], "image": []}

完善HTTP API说明

---

bot.py
config.py
conversation.py
drawing/sdwebui.py
universal.py

暂时抑制用户发送空消息时关于未定义conversation_handler的报错（转至log报错）
