lss233/kirara-ai

bot.py
chatbot.py

只登录一次，通过切换 conversation_id 和 parent_id 来实现上下文切换。

feat:single session

---

LICENSE

Resolve lss233/chatgpt-mirai-qq-bot#20.

Change to AGPL-3.0

---

bot.py
chatbot.py
config.py

- 支持配置响应格式
- 支持配置命令前缀
- 优化异常打印方式
- 智能识别 JSON 格式
- 重构了配置结构以自动检查配置
- 使用原生的异步 API
- 支持配置机器人是否回复消息
- 支持等待时间过久时自动发送消息

feat: use native async api for ChatGPT, better config

---

README.md
config.example.cfg
config.py

Support access_token for revChatGPT.V1

support access_token for revChatGPT.V1

---

README.md
config.example.cfg
config.py

support access token

---

.gitignore
bot.py
chatbot.py
config.py
docker-compose.yaml
manager.py
requirements.txt
utils/exithooks.py

style: code format

---

.gitignore
bot.py
manager.py
requirements.txt

为了优化登录逻辑、避免频繁登录造成账号导致账号损失，新增了登录缓存功能。
Close #166

新增：优化登录逻辑 & 登录缓存

---

.github/quickstarts/windows/scripts/初始化.cmd
.github/workflows/quickstart-windows.yml

This PR will make quickstart for windows bundle all dependencies, in order to make user download less stuff, avoid network failure

Quickstart: Bundle everything

---

middlewares/baiducloud.py
requirements.txt

修复了图片被编码的问题，增加了屏蔽原因

---

adapter/ms/bing.py

> 你好，这是Bing。Python是一种广泛使用的解释型、高级和通用的编程语言[^1^][1]。Python支持多种编程范型，包括结构化、过程式、反射式、面向对象和函数式编程[^1^][1]。Python还有一个巨大而广泛的标准库，可以用于各种应用程序开发，从简单的文字处理到人工智能[^2^][2] [^3^][4]。
> 你好，这是Bing。Python是一种广泛使用的解释型、高级和通用的编程语言[1]。Python支持多种编程范型，包括结构化、过程式、反射式、面向对象和函数式编程[1]。Python还有一个巨大而广泛的标准库，可以用于各种应用程序开发，从简单的文字处理到人工智能[2][4]。

使用正则表达式对Bing回复正文中的"[^1^]"等内容进行替换处理，提高可读性

---

README.md

个人测试通过，除了图片模式之外没有任何问题，图片模式也可以通过brew安装wkhtmltopdf解决，本地测试也没有问题，希望可以帮到使用Mac的小伙伴~
log：
===
显示效果：
===

新增Mac用户相关提示

---

.github/quickstarts/windows/scripts/初始化.cmd
.github/workflows/quickstart-windows.yml
adapter/ms/bing.py
bot.py
config.py
conversation.py
exceptions/__init__.py
manager/bot.py
renderer/renderer.py
utils/network.py
utils/text_to_img.py

- windows quickstart workflow
- code format

chore: update quickstart and code format

---

Unofficial.py
chatbot/chatgpt.py
config.example.cfg
config.py
manager/bot.py
requirements.txt

跟随[上游更新](https://github.com/acheong08/ChatGPT/releases/tag/4.0.0)支持GPT-4：
- 更新依赖包版本 ([diff1](https://github.com/lss233/chatgpt-mirai-qq-bot/commit/04de484cb85c1381cc6065ae50497a448b0ee2a1#diff-4d7c51b1efe9043e44439a949dfd92e5827321b34082903477fd04876edb7552R2))
- 添加配置项`gpt4`，为真时传入`model="gpt-4"`参数构造`ChatBot`，以使用GPT-4模型对话 ([diff2](https://github.com/lss233/chatgpt-mirai-qq-bot/commit/04de484cb85c1381cc6065ae50497a448b0ee2a1#diff-117426151e93a626f8b46bfdb3a95b3f4a62e5f4dd6e65975a7c50759bf04482R64), [diff3](https://github.com/lss233/chatgpt-mirai-qq-bot/pull/359/commits/e4ae545e3054e255a13ed4c0055276b16d12e521#diff-de8ee73f89fb72acbae15f495584d10893e8daaa381e8ef5959406e0fe7bd631R208))
- 将本项目依赖但在新版本`revChatGPT`中被移除的`Unofficial.py`复制至本地根目录 …

Support GPT-4

---

adapter/ms/bing.py

原有代码相当于重写了[EdgeGPT.Chatbot.ask()](https://github.com/acheong08/EdgeGPT/blob/9bde89605fed1f876d61bef670857f59d0051e16/src/EdgeGPT.py#L328)，应该是为了去除回答中一些特殊符号和适配分段发送功能   
没看其他地方的代码，如果不是为了适配分段发送，完全可以调用原库已封装的ask方法等返回完整的json数据后再处理符号
因为暂时不知道怎么和分段发送适配，就被迫把“剩余回复数”挪到消息末尾，应该无关紧要，后续有时间再去上游看看分段发送的实现
<details>
<summary>
完整json数据结构
</summary>
```
{
"type": 2,
"invocationId": "0",
"item": {
"messages": [
{
"text": "\u4e3a\u4f60\u5199\u8bd7,\u4e3a\u4f60\u5199\u8bcd",
"author": "user",
"from": {
"id": "xxxxxxxxxxx",
"name": null
},
"createdAt": "2023-03-27T10:55:17.5377854+00:00",
"timestamp": "2023-03-27T10:55:17.5349779+00:00",
"locale": "en-us",
"market": "en-us",
"region": "us",
"messageId": "e037a2af-f549-4724-a5c2-9b8451776516",
"requestId": "e037a2af-f549-4724-a5c2-9b8451776516",
"nlu": { …
```

[#439] fix:retrieve maximum Bing responses automatically

---

README.md
universal.py

1、文心一言部分写成了Bing
2、加入了新增加的AI模型（wiki里没有bard - Google Bard，作者记得加一下捏）
1、通过判断botManager中是否存在某些AI的账号来回复错误信息
2、poe AI只写了三个免费的模型，也许未来可以判断是否付费用户再加入付费模型（？）

1.让切换AI的错误提示只显示当前拥有的AI；2.修正部分readme信息

---

README.md
bot.py
config.py
middlewares/ratelimit.py
platforms/ariadne_bot.py
platforms/discord_bot.py
platforms/http_service.py
platforms/onebot_bot.py
platforms/telegram_bot.py
requirements.txt

support http service.

---

platforms/ariadne_bot.py
platforms/discord_bot.py
platforms/http_service.py
platforms/onebot_bot.py
platforms/telegram_bot.py
requirements.txt

1. Fix http response
2. upgrade poe-api to 0.2.7

Fix http response

---

utils/vits_tts.py

- 移除文本中包含[LENGTH=1.4]，修复语速调节无效的问题
- auto模式直接返回text，减少不必要的匹配

fix:移除文本中包含[LENGTH=1.4]，auto直接返回text

---

.gitignore
config.py
constants.py
conversation.py
manager/bot.py
universal.py

Feat support ping trigger

---

adapter/quora/poe.py
manager/bot.py

1. If the last ask exceeds 1 hour, reset the bot first and then continue the ask.
2. Reset bot and retry asking while poe connection is broken.

Try to fix poe connection error.

---

README.md
platforms/http_service.py
requirements.txt

1. support voice response.
2. add asyn api for http-service.

Feat optimize http service

---

constants.py
platforms/discord_bot.py
platforms/http_service.py
platforms/onebot_bot.py
platforms/telegram_bot.py
universal.py
utils/edge_tts.py
utils/text_to_speech.py
utils/vits_tts.py

Fix http not returning mp3 when mirai and http are enabled at the same time.

Fix voice response

---

manager/bot.py

Fix 自动推测AI不支持slack-claude

---

utils/vits_tts.py

https://github.com/lss233/chatgpt-mirai-qq-bot/issues/753#issue-1695594919

update:Use the new api to verify the id

---

manager/bot.py

很抱歉还得提交一次(＠_＠;)，昨天提交的代码有点问题，是GitHub Copilot自动补全的，但它却能正常运行…(⊙_⊙;)…
#758 
#757

Fix auto detect default ai

---

config.py
framework/universal.py
prompts/default.yml

https://github.com/lss233/chatgpt-mirai-qq-bot/pull/755#issuecomment-1543297068

feat: add default prompt preset

---

README.md

更新图吧狂喜之旧手机部署教程
-使用AidLux，理论上来说只要是安卓的Linux模拟器都可以(Termux，Anbox，UserLAnd，etc.)
-AidLux可以直接使用一键部署脚本
-debian系linux也可以直接使用一键部署脚本

doc: 提供一种新的部署思路，方式和一键部署脚本。

---

adapter/quora/poe.py
constants.py

POE:fix-adapter-poe-gpt4

---

requirements.txt

[FIX] poe解析失败

---

requirements.txt

https://github.com/acheong08/ChatGPT/pull/1425

chore(deps): upgrade revChatGPT version to support new OpenAI models

---

requirements.txt

- 修复poe payload error
- 修复poe download too many times
- ：）

FIX: poe error

---

Dockerfile
adapter/chatgpt/web.py
adapter/common/chat_helper.py
adapter/gpt4free/g4f_helper.py
adapter/gpt4free/gpt4free.py
adapter/quora/poe.py
config.example.cfg
config.py
conversation.py
manager/bot.py
requirements.txt

add gpt4free support
